apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrf
  template:
    metadata:
      labels:
        app: nrf
    spec:
      containers:
      - name: nrf
        image: openverso/open5gs:latest
        command:
        - /opt/open5gs/bin/open5gs-nrfd
